// This page is equevalent to _app.js
import React from "react";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AuthProvider from "./context/AuthProvider";
import localFont from "next/font/local";
import "./globals.css";
import { options } from "./api/auth/[...nextauth]/options";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full bg-white">
      <body
        className={
          (`${geistSans.variable} ${geistMono.variable} antialiased`, "h-full")
        }
      >
        <AntdRegistry>
          <AuthProvider>{children}</AuthProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
